drop table clients;

create table if not exists clients
(
    client_id    bigint generated by default as identity primary key,
    firstname    varchar(32) not null,
    middlename   varchar(32),
    lastname     varchar(32) not null,
    phone_number varchar(15) not null,
    constraint uq_phone_number unique (phone_number)
);


